### ISSUE TITLE
version.txt

### ISSUE THREAD

**Issue by MADONOKOUKI** [NiryoRobotics/ned_ros#4]
Hi, do you know how to get the version.txt?
I read this tutorial and execute the ros command as bellow. (https://www.docs.niryo.com/dev/ros/source/ros/niryo_robot_bringup.html )
I tried to launch the simulation and open niryo studio to manipulate via GUI.
when I execute this command, I fail on RPI4 at ubuntu 18.04
By the way, this distributed image can not open at the RPI4.
https://drive.google.com/u/0/uc?export=download&confirm=lP28&id=1r96st0ShNO2HXrpGHYPFpUScH4hlnl2u
`
roslaunch niryo_robot_bringup niryo_ned_robot.launch
`
```
ubuntu@ubuntu:~/catkin_ws_niryo_ned$ roslaunch niryo_robot_bringup niryo_ned_robot.launch
... logging to /home/ubuntu/.ros/log/41be2b18-71f4-11eb-9759-dca632bab4aa/roslaunch-ubuntu-4142.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 332, in main
    p.start()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 289, in start
    self._start_infrastructure()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 238, in _start_infrastructure
    self._load_config()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 144, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 634, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 669, in _recurse_load
    default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 679, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 271, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/loader.py", line 476, in param_value
    with open(textfile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/niryo/.config/niryo/version/version.txt'
```

**Comment by ValentinPitre** [comment]
Please use: roslaunch niryo_robot_bringup desktop_rviz_simulation.launch 
instead of the niryo_ned_robot.launch dedicated to a real robot
